pub const TIME_SCALER_ON_RAISED_CARD_LINE: f32 = 0.01;
pub const TIME_SCALER_ON_CARD_DRAG: f32 = 0.05;

pub const HELD_CARD_ROTATION_FACTOR: f32 = 0.5;
pub const CARD_HOVER_HEIGHT: f32 = 80.0;

pub const ON_HOVER_SCALE_FACTOR: f32 = 1.4;
pub const ON_HOVER_SCALE_DURATION: f32 = 0.04;
pub const ON_HOVER_CANCEL_SCALE_DURATION: f32 = 0.03;
pub const ON_HOVER_POSITION_TWEEN_DURATION: f32 = 0.2;
pub const ON_HOVER_CANCEL_POSITION_TWEEN_DURATION: f32 = 0.1;
pub const GO_BACK_TO_PLACE_TWEEN_DURATION: f32 = 0.04;

pub const CARD_SLIDE_ON_ORIGIN_SET_DURATION: f32 = 0.2;
